### ISSUE TITLE
no case clause matching: "Miles&Smiles"

### ISSUE THREAD

**Issue by encku** [Chatatata/iyzico#13]
(buy_buddy) lib/iyzico/model/card.ex:89: Iyzico.Card.get_card_assoc/1
        (buy_buddy) lib/iyzico/endpoint/bin_inquiry.ex:146: Iyzico.BinInquiry.serialize_resp/1
        (buy_buddy) lib/buy_buddy/payment/iyzico.ex:195: BuyBuddy.Payment.Iyzico.card_info/3
        (buy_buddy) src/orders/overview/card_info_controller.ex:119: BuyBuddy.Orders.Overview.CardInfoController.show/2
        (buy_buddy) src/orders/overview/card_info_controller.ex:1: BuyBuddy.Orders.Overview.CardInfoController.action/2
        (buy_buddy) src/orders/overview/card_info_controller.ex:1: BuyBuddy.Orders.Overview.CardInfoController.phoenix_controller_pipeline/2
        (buy_buddy) lib/buy_buddy/endpoint.ex:1: BuyBuddy.Endpoint.instrument/4
        (buy_buddy) lib/phoenix/router.ex:261: BuyBuddy.Router.dispatch/2

In my opinion,

No need to define every family as a atom, pass the parameter directly.

**Comment by Chatatata** [comment]
In Elixir, every time you create a binary, it needs to allocate a memory for the particular object. Since they're garbage collected, that might be a bottleneck depending on use case. OTOH, atoms are not GC-ed, and typespecs explicitly show all of the possibilities, which could be subject to static analysis with tools like Dialyzer.

Furkan Ençkü <notifications@github.com> şunları yazdı (13 Ara 2017 17:14):
